### PR TITLE
1.3 - Updated to 1.10.2, general improvements

### PR DESCRIPTION
**Pull request by elix-x**
-Updated to 1.10.2.
-Updated to java 7.
-Added modes of chunk generation (zone/radius).
-Improved command in general (support for modes, relative coordinates).
-Improved way it tells forge it's server side only.
-MC version does not belong to mod version, SEMVER will be confused.
-Updated README to conform to additions.

### CODE REVIEW

**Comment by LuxusDarkangel** [comment]
You should add this fix too: [#23](https://github.com/gecgooden/chunkgen/pull/23) as this is only generating a "flat" chunk, and that's basically... useless...

**Comment by elix-x** [comment]
Help is already fixed and i will include #23.

**Comment by LuxusDarkangel** [comment]
Have you an ETA? I would like to use this.

**Comment by elix-x** [comment]
Not quite.

**Comment by gecgooden** [comment]
I've merged this commit and added a new build to the release section. 
It'll be added to CurseForge soon.

**Comment by elix-x** [comment]
Nice!
And i saw your reply over on #23, so i'll leave it.

**Pull request merged**
